version: "3"

services:
   ubuntu:
        image: ubuntu
        container_name: ubuntu
        ports:
            - 3333:3333
        restart: on-failure
        volumes:
            repo:/home/user/ft_containers

volumes:
    repo:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/Users/albgarci/Documents/ft_containers
