version: "3"

services:
   ubuntu:
        image: ub
        container_name: ubuntu
        build: ./
        ports:
            - 3333:3333
        restart: on-failure
        volumes:
            - repo:$(DLC_WORK_VOLUME_DESTINATION)
            - clang:/clang_15
        working_dir: $(DLC_WORKING_DIR)
        tty: true

volumes:
    repo:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $(DLC_WORK_VOLUME_ORIGIN)
    clang:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $(PWD)/clang_15
