version: "3"

services:
   ubuntu:
        image: ub
        container_name: ubuntu
        build: ./
        ports:
            - 3333:3333
        restart: on-failure
        volumes:
            - repo:/home/ft_containers
            - clang:/clang_15
        working_dir: /home/ft_containers
        tty: true

volumes:
    repo:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $HOME/Documents/ft_containers
    clang:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $PWD/clang_15
